name: Aone Open Plugin 发布

params:
  plugin:
    type: string
    default: "relay-kanban"
  version:
    type: string
    required: true
  tag:
    type: string
    default: "latest"
    options: [ "beta", "latest" ]
  token:
    type: string
    required: true
    sensitive: true
  env:
    type: string
    default: "prod"
    options: [ "daily", "pre", "prod" ]
  changelog:
    type: string
    default: ""
  config:
    type: string
    default: "{}"

jobs:
  publish:
    name: 发布 Plugin Package
    steps:
      - uses: checkout
      - uses: setup-env
        inputs:
          node-version: 18
      - uses: aone-plugin-publish@1.0.1
        inputs:
          path: "."
          plugin: $params.plugin
          packageName: "relay-kanban"
          version: $params.version
          tag: $params.tag
          token: $params.token
          env: $params.env
          changelog: $params.changelog
          config: $params.config
